In [2]:
import pandas as pd
from Tools import handleTime

In [3]:
table = pd.read_csv('../training_20min_avg_travel_time.csv')

In [6]:
table['time_start'] = pd.to_datetime(
    table.time_window.apply(lambda x: x[1:-1].split(',')[0]))

In [23]:
table['dayofyear'] = table.time_start.apply(lambda x: x.dayofyear)
table['hour'] = table.time_start.apply(lambda x: x.hour)
table['minute'] = table.time_start.apply(lambda x: x.minute)

In [25]:
days = {
    'day': []
}
hours = [6, 7]
for day,df in table.groupby(['dayofyear']):
    days['day'] += day
    
    for hour in hours:
        for minute in table['minute'].unique():
            ind = (table['minute'] == minute) & (table['hour'] == hour)
            for t in table[ind].groupby(['intersection_id', 'tollgate_id']):
                if(len(t) == 0):
                    days[day]

0        201
1        201
2        201
3        201
4        201
5        201
6        201
7        201
8        201
9        201
10       201
11       201
12       201
13       201
14       201
15       201
16       201
17       201
18       201
19       201
20       201
21       201
22       201
23       201
24       201
25       201
26       201
27       201
28       201
29       201
        ...
25114    290
25115    290
25116    290
25117    291
25118    291
25119    291
25120    291
25121    291
25122    291
25123    291
25124    291
25125    291
25126    291
25127    291
25128    291
25129    291
25130    291
25131    291
25132    291
25133    291
25134    291
25135    291
25136    291
25137    291
25138    291
25139    291
25140    291
25141    291
25142    291
25143    291
Name: dayofyear, dtype: int64

In [26]:
table['minute'].unique()

array([ 0, 20, 40])

In [21]:
Test['t1'] = table.avg_travel_time

In [27]:
table

,intersection_id,tollgate_id,time_window,avg_travel_time,time_start,hour,minute,dayofyear
0,B,3,"[2016-07-19 00:00:00,2016-07-19 00:20:00)",70.85,2016-07-19 00:00:00,0,0,201
1,B,3,"[2016-07-19 00:20:00,2016-07-19 00:40:00)",148.79,2016-07-19 00:20:00,0,20,201
2,B,3,"[2016-07-19 01:40:00,2016-07-19 02:00:00)",93.72,2016-07-19 01:40:00,1,40,201
3,B,3,"[2016-07-19 02:00:00,2016-07-19 02:20:00)",67.81,2016-07-19 02:00:00,2,0,201
4,B,3,"[2016-07-19 02:40:00,2016-07-19 03:00:00)",167.55,2016-07-19 02:40:00,2,40,201
5,B,3,"[2016-07-19 03:40:00,2016-07-19 04:00:00)",98.49,2016-07-19 03:40:00,3,40,201
6,B,3,"[2016-07-19 04:00:00,2016-07-19 04:20:00)",96.67,2016-07-19 04:00:00,4,0,201
7,B,3,"[2016-07-19 04:20:00,2016-07-19 04:40:00)",53.15,2016-07-19 04:20:00,4,20,201
8,B,3,"[2016-07-19 04:40:00,2016-07-19 05:00:00)",55.25,2016-07-19 04:40:00,4,40,201
9,B,3,"[2016-07-19 05:00:00,2016-07-19 05:20:00)",209.66,2016-07-19 05:00:00,5,0,201
10,B,3,"[2016-07-19 06:00:00,2016-07-19 06:20:00)",145.94,2016-07-19 06:00:00,6,0,201
11,B,3,"[2016-07-19 06:20:00,2016-07-19 06:40:00)",127.35,2016-07-19 06:20:00,6,20,201
12,B,3,"[2016-07-19 06:40:00,2016-07-19 07:00:00)",97.20,2016-07-19 06:40:00,6,40,201
13,B,3,"[2016-07-19 07:00:00,2016-07-19 07:20:00)",118.43,2016-07-19 07:00:00,7,0,201
14,B,3,"[2016-07-19 07:20:00,2016-07-19 07:40:00)",82.63,2016-07-19 07:20:00,7,20,201
15,B,3,"[2016-07-19 07:40:00,2016-07-19 08:00:00)",110.50,2016-07-19 07:40:00,7,40,201
16,B,3,"[2016-07-19 08:00:00,2016-07-19 08:20:00)",125.76,2016-07-19 08:00:00,8,0,201
17,B,3,"[2016-07-19 08:20:00,2016-07-19 08:40:00)",141.33,2016-07-19 08:20:00,8,20,201
18,B,3,"[2016-07-19 08:40:00,2016-07-19 09:00:00)",176.08,2016-07-19 08:40:00,8,40,201
19,B,3,"[2016-07-19 09:00:00,2016-07-19 09:20:00)",165.29,2016-07-19 09:00:00,9,0,201
20,B,3,"[2016-07-19 09:20:00,2016-07-19 09:40:00)",127.38,2016-07-19 09:20:00,9,20,201
21,B,3,"[2016-07-19 09:40:00,2016-07-19 10:00:00)",117.83,2016-07-19 09:40:00,9,40,201
22,B,3,"[2016-07-19 10:00:00,2016-07-19 10:20:00)",98.92,2016-07-19 10:00:00,10,0,201
23,B,3,"[2016-07-19 10:20:00,2016-07-19 10:40:00)",113.00,2016-07-19 10:20:00,10,20,201
24,B,3,"[2016-07-19 10:40:00,2016-07-19 11:00:00)",98.15,2016-07-19 10:40:00,10,40,201
25,B,3,"[2016-07-19 11:00:00,2016-07-19 11:20:00)",95.98,2016-07-19 11:00:00,11,0,201
26,B,3,"[2016-07-19 11:20:00,2016-07-19 11:40:00)",84.36,2016-07-19 11:20:00,11,20,201
27,B,3,"[2016-07-19 11:40:00,2016-07-19 12:00:00)",96.54,2016-07-19 11:40:00,11,40,201
28,B,3,"[2016-07-19 12:00:00,2016-07-19 12:20:00)",144.87,2016-07-19 12:00:00,12,0,201
29,B,3,"[2016-07-19 12:20:00,2016-07-19 12:40:00)",136.36,2016-07-19 12:20:00,12,20,201
...,...,...,...,...,...,...,...,...
25114,C,3,"[2016-10-16 21:00:00,2016-10-16 21:20:00)",151.08,2016-10-16 21:00:00,21,0,290
25115,C,3,"[2016-10-16 22:20:00,2016-10-16 22:40:00)",121.35,2016-10-16 22:20:00,22,20,290
25116,C,3,"[2016-10-16 23:00:00,2016-10-16 23:20:00)",261.92,2016-10-16 23:00:00,23,0,290
25117,C,3,"[2016-10-17 00:20:00,2016-10-17 00:40:00)",184.64,2016-10-17 00:20:00,0,20,291
25118,C,3,"[2016-10-17 08:40:00,2016-10-17 09:00:00)",198.63,2016-10-17 08:40:00,8,40,291
25119,C,3,"[2016-10-17 09:40:00,2016-10-17 10:00:00)",218.18,2016-10-17 09:40:00,9,40,291
25120,C,3,"[2016-10-17 10:00:00,2016-10-17 10:20:00)",220.20,2016-10-17 10:00:00,10,0,291
25121,C,3,"[2016-10-17 10:40:00,2016-10-17 11:00:00)",149.87,2016-10-17 10:40:00,10,40,291
25122,C,3,"[2016-10-17 12:00:00,2016-10-17 12:20:00)",104.38,2016-10-17 12:00:00,12,0,291
25123,C,3,"[2016-10-17 12:20:00,2016-10-17 12:40:00)",142.40,2016-10-17 12:20:00,12,20,291
25124,C,3,"[2016-10-17 12:40:00,2016-10-17 13:00:00)",149.15,2016-10-17 12:40:00,12,40,291
25125,C,3,"[2016-10-17 13:20:00,2016-10-17 13:40:00)",169.18,2016-10-17 13:20:00,13,20,291
25126,C,3,"[2016-10-17 13:40:00,2016-10-17 14:00:00)",149.21,2016-10-17 13:40:00,13,40,291
25127,C,3,"[2016-10-17 14:20:00,2016-10-17 14:40:00)",150.72,2016-10-17 14:20:00,14,20,291
25128,C,3,"[2016-10-17 14:40:00,2016-10-17 15:00:00)",191.02,2016-10-17 14:40:00,14,40,291
25129,C,3,"[2016-10-17 15:00:00,2016-10-17 15:20:00)",126.44,2016-10-17 15:00:00,15,0,291
25130,C,3,"[2016-10-17 16:00:00,2016-10-17 16:20:00)",171.02,2016-10-17 16:00:00,16,0,291
25131,C,3,"[2016-10-17 16:20:00,2016-10-17 16:40:00)",311.18,2016-10-17 16:20:00,16,20,291
25132,C,3,"[2016-10-17 16:40:00,2016-10-17 17:00:00)",198.46,2016-10-17 16:40:00,16,40,291
25133,C,3,"[2016-10-17 17:20:00,2016-10-17 17:40:00)",122.02,2016-10-17 17:20:00,17,20,291
25134,C,3,"[2016-10-17 18:00:00,2016-10-17 18:20:00)",173.74,2016-10-17 18:00:00,18,0,291
25135,C,3,"[2016-10-17 18:40:00,2016-10-17 19:00:00)",526.49,2016-10-17 18:40:00,18,40,291
25136,C,3,"[2016-10-17 19:00:00,2016-10-17 19:20:00)",101.73,2016-10-17 19:00:00,19,0,291
25137,C,3,"[2016-10-17 19:40:00,2016-10-17 20:00:00)",187.43,2016-10-17 19:40:00,19,40,291
25138,C,3,"[2016-10-17 20:00:00,2016-10-17 20:20:00)",209.32,2016-10-17 20:00:00,20,0,291
25139,C,3,"[2016-10-17 20:40:00,2016-10-17 21:00:00)",194.49,2016-10-17 20:40:00,20,40,291
25140,C,3,"[2016-10-17 21:00:00,2016-10-17 21:20:00)",195.00,2016-10-17 21:00:00,21,0,291
25141,C,3,"[2016-10-17 21:20:00,2016-10-17 21:40:00)",159.44,2016-10-17 21:20:00,21,20,291
25142,C,3,"[2016-10-17 22:20:00,2016-10-17 22:40:00)",185.25,2016-10-17 22:20:00,22,20,291
25143,C,3,"[2016-10-17 22:40:00,2016-10-17 23:00:00)",150.53,2016-10-17 22:40:00,22,40,291